# Generated by Django 6.0.5 on 2026-05-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_teacher_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('student', models.PositiveIntegerField(max_length=100, null=True)),
            ],
        ),
    ]
