# Generated by Django 6.0.4 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('adress', models.CharField(max_length=120, null=True)),
                ('department', models.CharField(max_length=120, null=True)),
                ('gurdian_name', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
